draft: false
acme:
  email_account: caseybailey@gmail.com
  staging: false # set to TRUE while testing or you will be banned for a week!
profiles:
  - name: hetzner
    provider: hetzner
    provider_options:
      auth_token: ${{ HETZNER_DNS_AUTH_TOKEN }}
certificates:
  - domains:
      - "*.doggr.pro"
      - doggr.pro
    profile: hetzner
