name: Heap Overrun CICD

on:
  push:
    branches: [ master, develop, sslpractice, sslpracticenew ]
  pull_request:
    branches: [ master, develop, sslpractice ]

env:
  CARGO_TERM_COLOR: always #Pretty-print the logs

jobs:

  # Run cargo test on our backend and stop deployment if it fails
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo target dir
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}


      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install sqlx-cli
        run: cargo install sqlx-cli

      - name: Run migrations
        run: sqlx migrate run
        working-directory: backend
        env:
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/${{ secrets.POSTGRES_DB }}

      - name: Change to backend directory
        run: cd backend

      - name: Build
        run: cargo build --verbose
        working-directory: backend
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/${{ secrets.POSTGRES_DB }}

      - name: Run tests
        run: cargo test --verbose
        working-directory: backend
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/${{ secrets.POSTGRES_DB }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          # Live site IP address (Normally this would be tied to a domain name like doggr.pro)
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          # This is explicitly an SSH private key stored inside of Github Repo's "Repository Secrets"
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            # Extract PATH and save it to a temp file
            grep '^PATH=' /etc/environment > /tmp/environment.tmp
            # Append the environment variables
            echo "API_HOST=${{ secrets.API_HOST }}" >> /tmp/environment.tmp
            echo "API_PORT=${{ secrets.API_PORT }}" >> /tmp/environment.tmp
            echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> /tmp/environment.tmp
            echo "LOCAL_DATABASE_URL=\"${{ secrets.LOCAL_DATABASE_URL }}\"" >> /tmp/environment.tmp
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> /tmp/environment.tmp
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> /tmp/environment.tmp
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /tmp/environment.tmp
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /tmp/environment.tmp
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> /tmp/environment.tmp
            echo "SALT=${{ secrets.SALT }}" >> /tmp/environment.tmp
            echo "SQLX_OFFLINE=${{ secrets.SQLX_OFFLINE }}" >> /tmp/environment.tmp
            # Move the temp file to /etc/environment
            mv /tmp/environment.tmp /etc/environment
            
            sudo apt-get install -y build-essential libssl-dev pkg-config
            
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            
            cargo install sqlx-cli
            
            mkdir -p ~/workspace
            cd ~/workspace/
            rm -rf ./class_project
            git clone --depth=1 --branch sslpracticenew https://github.com/pdx-cs-rust-web/class_project class_project  # Clone the latest
            cd class_project
            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml build --no-cache --compress
            docker compose -f docker-compose.prod.yaml up -d
            echo "Do not forget to migrate"
  
            
            
            
            
