name: Heap Overrun CICD

on:
  push:
    branches: [master, develop, sslpractice, sslpracticenew]
  pull_request:
    branches: [master, develop, sslpractice]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@localhost/test

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo target dir
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}


      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Change to backend directory
        run: cd backend

      - name: Build
        run: cargo build --verbose
        working-directory: backend
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/${{ secrets.POSTGRES_DB }}

      - name: Run tests
        run: cargo test --verbose
        working-directory: backend
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/${{ secrets.POSTGRES_DB }}

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          # Live site IP address (Normally this would be tied to a domain name like doggr.pro)
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          # This is explicitly an SSH private key stored inside of Github Repo's "Repository Secrets"
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            echo 'export API_HOST=${{ secrets.API_HOST }}' >> ~/.bashrc
            echo 'export API_PORT=${{ secrets.API_PORT }}' >> ~/.bashrc
            echo 'export DATABASE_URL="${{ secrets.DATABASE_URL }}"' >> ~/.bashrc
            echo 'export LOCAL_DATABASE_URL="${{ secrets.LOCAL_DATABASE_URL }}"' >> ~/.bashrc
            echo 'export POSTGRES_DB=${{ secrets.POSTGRES_DB }}' >> ~/.bashrc
            echo 'export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' >> ~/.bashrc
            echo 'export POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> ~/.bashrc
            echo 'export SALT=${{ secrets.SALT }}' >> ~/.bashrc
            echo 'export SQLX_OFFLINE=${{ secrets.SQLX_OFFLINE }}' >> ~/.bashrc
            source ~/.bashrc
            
            export API_HOST=${{ secrets.API_HOST }}
            export API_PORT=${{ secrets.API_PORT }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export LOCAL_DATABASE_URL=${{ secrets.LOCAL_DATABASE_URL }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export SALT=${{ secrets.SALT }}
            export SQLX_OFFLINE=${{ secrets.SQLX_OFFLINE }}
            
            sudo apt-get install -y build-essential libssl-dev pkg-config
            
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            
            cargo install sqlx-cli
            
            mkdir -p ~/workspace
            cd ~/workspace/
            rm -rf ./class_project
            git clone --depth=1 --branch sslpracticenew https://github.com/pdx-cs-rust-web/class_project class_project  # Clone the latest
            cd class_project
            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml build --no-cache --compress
            docker compose -f docker-compose.prod.yaml up -d
            echo "Do not forget to migrate"
  
            
            
            
            
